sudo: false
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - 0.10
before_install:
  # for debugging travis, just in case
  - 'env'
  # verify that secrets.tar.enc cannot be decrypted without the key (and that the key isn't committed!): decryption should fail
  - './bin/decrypt_secrets && echo "Decrypted our secrets without the key?! Oops, time to change our passwords" || true'
deploy:
  # http://stackoverflow.com/questions/15918098/travis-ci-with-amazon-elastic-beanstalk
  provider: elasticbeanstalk
  access_key_id: AKIAJTY2CDAZSKPJNNTQ
  secret_access_key:
    secure: "O7w+1MjgkfMGydqKzH+5gZn3Y+s6zEeGmmOlNVcoFUvKAfgmNkI9Nd4nIKhJCyz2I24u9KS5TcYnhB3IFjDlZt8AlVptJwwtqipxEWDJdP3w98qehsIfmy7dOCxwekduJYt4+LqubWsCWmGYZ3LnLyVNaFpdUfOAXuXZXilhKkM="
  region: us-east-1
  app: swarm-server-sails
  env: swarm-server-sails-pre
  bucket_name: elasticbeanstalk-us-east-1-travisci-swarmsim-server-sails
  on:
    branch: master
    node: 0.10
